# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  batch: true
  branches:
    include:
    - master
    - feature/*
    exclude:
    - gh-pages

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'Windows-latest'

    variables:
      solution: '**/src/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:

    - task: NuGetToolInstaller@1

    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk 3.1.2'
      inputs:
        packageType: sdk
        version: 3.1.201

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration) /p:Platform="$(buildPlatform)"'

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **\bin\$(buildConfiguration)\*.nupkg
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        flattenFolders: true

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop
